name: Test ML Flask App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Flask==2.2.2 numpy==1.24.3 scikit-learn==1.2.2 cloudpickle mlflow

      - name: Run tests
        run: python tests/test-script.py
